"""Canonical Talea schema values and annotation resolution."""

from talea.schema.nodes import (
    AliasSchema,
    ConstrainedSchema,
    DataclassField,
    DataclassSchema,
    EnumSchema,
    FixedTupleSchema,
    LiteralSchema,
    LiteralValue,
    MappingSchema,
    NamedReferenceSchema,
    NamedSchemaIdentity,
    PrimitiveKind,
    PrimitiveSchema,
    Schema,
    SequenceKind,
    SequenceSchema,
    SpecReferenceSchema,
    TaggedUnionBranch,
    TaggedUnionSchema,
    TypeCheckMode,
    TypedDictField,
    TypedDictSchema,
    TypeSchema,
    UnionSchema,
    VariadicTupleSchema,
)
from talea.schema.resolution import (
    AnnotationResolutionError,
    ConstraintDeclarationError,
    TaggedUnionDeclarationError,
    resolve_annotation,
)

__all__ = [
    "AliasSchema",
    "AnnotationResolutionError",
    "ConstrainedSchema",
    "ConstraintDeclarationError",
    "DataclassField",
    "DataclassSchema",
    "TaggedUnionDeclarationError",
    "EnumSchema",
    "FixedTupleSchema",
    "LiteralSchema",
    "LiteralValue",
    "MappingSchema",
    "NamedReferenceSchema",
    "NamedSchemaIdentity",
    "PrimitiveKind",
    "PrimitiveSchema",
    "Schema",
    "SequenceKind",
    "SequenceSchema",
    "SpecReferenceSchema",
    "TaggedUnionBranch",
    "TaggedUnionSchema",
    "TypeCheckMode",
    "TypeSchema",
    "TypedDictField",
    "TypedDictSchema",
    "UnionSchema",
    "VariadicTupleSchema",
    "resolve_annotation",
]
