#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi
if [ -d 'talea.egg-info' ] ; then
    rm -r talea.egg-info
fi
if [ -d '.hypothesis' ] ; then
    rm -r .hypothesis
fi
if [ -d '.mypy_cache' ] ; then
    rm -r .mypy_cache
fi
if [ -d '.pytest_cache' ] ; then
    rm -r .pytest_cache
fi
if [ -d '.ruff_cache' ] ; then
    rm -r .ruff_cache
fi

find talea -type f -name "*.py[co]" -delete
find talea -type d -name __pycache__ -delete
